config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'session#login'
  resources :calcs
  post 'session/create'
  get 'session/logout'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/session_controller.rb
# frozen_string_literal: true

class SessionController < ApplicationController
  skip_before_action :require_login, only: %i[login create]

  def login; end

  def create
    user = User.find_by(username: params[:login])

    if user&.authenticate(params[:password])
      sign_in user
      redirect_to calcs_path # calcs#index
    else
      # flash.now[:danger] = 'Неверный логин или пароль'
      redirect_to root_path, notice: 'Неверный логин или пароль'
    end
  end

  def logout
    sign_out
    redirect_to root_path
  end
end

app/helpers/session_helper.rb
# frozen_string_literal: true

module SessionHelper
  def sign_in(user)
    cookies.signed[:user_id] = { value: user.id, expires: 20.days }
    user.update_last_login_at
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.signed[:user_id] = nil
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end
end

app/views/session/login.html.erb
<% flash.each do |_type, msg| %>
  <p style="color: red"><%= msg %></p>
<% end %>

<%= form_with url: session_create_url, method: :post, local: true do |f| %>
  <%= f.text_field :login, required: true, label: 'Логин' %>
  <%= f.password_field :password, required: true, label: 'Пароль' %>
  <%= f.submit 'Войти' %>
<% end %>
<p><%= link_to 'Зарегистрироваться', new_user_path %></p>
<p><%= link_to 'Список пользователей', users_path %></p>
<p><%= link_to 'Calcs', calcs_path %></p>