config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'session#login'
  resources :calcs
  post 'session/create'
  get 'session/logout'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/calc.rb
# frozen_string_literal: true

class EquationOfNumberAndSequenceNumberValidator < ActiveModel::Validator
  def validate(record)
    # добавлена проверка на равенство nil, т. к. в ином случае в тестах модуля MaincontrResult в файле maincontr_result_spec.rb возникает ошибка, связанная с невозможностью применить .split к объекту nil (т. е. query_sequence не инициализирован?)
    return unless (!record.query_sequence.nil? ? record.query_sequence.split.map(&:to_i).size : 'for tests of this model') != record.query_number.to_i

    record.errors.add :base, 'Количество введённых чисел последовательности не соответствует тому, что было введено'
  end
end

class Calc < ApplicationRecord
  belongs_to :user

  validates :query_number, :query_sequence, presence: { message: 'не может быть пустым' } # проверка на обязательное наличие полей
  validates :query_sequence, uniqueness: true
  validates :sequences, :maxsequence, :sequences_number, presence: true

  validates :query_number, format: { with: /\A\d+\z/, message: 'должно быть натуральным числом' }

  @ptrn_list_and_error_messages = [
    { ptrn: /\A[\s\d]+\z/, err_msg: 'состоит только из натуральных чисел, разделённых пробелами' }
  ]

  @ptrn_list_and_error_messages.each do |el|
    validates :query_sequence, format: { with: el[:ptrn], message: el[:err_msg] }
  end

  validates_with EquationOfNumberAndSequenceNumberValidator

  # Статический метод
  class << self
    def add_number_bd(params, user_id)
      number = params[:query_number].to_i
      array = params[:query_sequence].split.map(&:to_i)
      enum = array.slice_when do |before, after|
        before_mod = is_square?(before)
        after_mod = is_square?(after)
        (!before_mod && after_mod) || (before_mod && !after_mod)
      end

      sequences = enum.to_a.select { |array| array.any? { |element| is_square?(element) } }

      create query_number: number, query_sequence: params[:query_sequence], sequences: JSON.generate(sequences),
             maxsequence: JSON.generate(sequences.max_by(&:size)), sequences_number: sequences.size,
             user_id:
    end

    def evaluate(params, user_id)
      number = params[:query_number].to_i
      array = params[:query_sequence].split.map(&:to_i)
      enum = array.slice_when do |before, after|
        before_mod = is_square?(before)
        after_mod = is_square?(after)
        (!before_mod && after_mod) || (before_mod && !after_mod)
      end

      sequences = enum.to_a.select { |array| array.any? { |element| is_square?(element) } }

      { query_number: number, query_sequence: params[:query_sequence], sequences: JSON.generate(sequences),
        maxsequence: JSON.generate(sequences.max_by(&:size)), sequences_number: sequences.size,
        user_id: }
    end

    private

    def is_square?(x)
      (Math.sqrt(x) % 1).zero?
    end
  end
end

app/controllers/calcs_controller.rb
# frozen_string_literal: true

class CalcsController < ApplicationController
  before_action :set_calc, only: %i[show edit update destroy]

  # GET /calcs or /calcs.json
  def index
    @calcs = Calc.all
  end

  # GET /calcs/1 or /calcs/1.json
  def show; end

  # GET /calcs/new
  def new
    @calc = Calc.new
  end

  # GET /calcs/1/edit
  def edit; end

  # POST /calcs or /calcs.json
  def create
    @calc = Calc.add_number_bd(params, current_user.id)

    respond_to do |format|
      if @calc.save
        format.html { redirect_to calc_url(@calc), notice: 'Calc was successfully created.' }
        format.json { render :show, status: :created, location: @calc }
      else
        # format.html { render :new, status: :unprocessable_entity }
        format.html do
          flash[:alert] ||= []
          @calc.errors.each do |error|
            flash[:alert] << [-1, error.full_message, nil, error.details[:value]]
          end
          redirect_to new_calc_path
        end
        format.json { render json: @calc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calcs/1 or /calcs/1.json
  def update
    respond_to do |format|
      if @calc.update(Calc.evaluate(params, current_user.id))
        format.html { redirect_to calc_url(@calc), notice: 'Calc was successfully updated.' }
        format.json { render :show, status: :ok, location: @calc }
      else
        format.html do
          flash[:alert] ||= []
          @calc.errors.each do |error|
            flash[:alert] << [-1, error.full_message, nil, error.details[:value]]
          end
          redirect_to edit_calc_path(@calc.id)
        end
        format.json { render json: @calc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calcs/1 or /calcs/1.json
  def destroy
    @calc.destroy

    respond_to do |format|
      format.html { redirect_to calcs_url, notice: 'Calc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_calc
    @calc = Calc.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def calc_params
    params.require(:calc).permit(:query_number, :query_sequence)
  end
end

app/helpers/calcs_helper.rb
# frozen_string_literal: true

module CalcsHelper
end

app/views/calcs/_calc.html.erb
<div id="<%= dom_id calc %>">

  <p>
    <strong>Input number of elemets of sequence:</strong>
    <%= calc.query_number %>
  </p>

  <p>
    <strong>Input sequence</strong>
    <%= calc.query_sequence %>
  </p>

  <h3>Результат:</h3>

  <% if JSON.parse(calc.sequences).empty? %>
  <h3>последовательностей не найдено</h3>
  <% else %>
    <table>
      <tr>
        <td><strong>последовательности</strong></td>
        <td><%= calc.sequences %></td>
      </tr>
      <tr>
        <td><strong>максимальная последовательность</strong></td>
        <td><%= calc.maxsequence %></td>
      </tr>
      <tr>
        <td><strong>количество последовательностей</strong></td>
        <td><%= calc.sequences_number %></td>
      </tr>
    </table>
  <% end %>

</div>

app/views/calcs/_form.html.erb
<main>
  <div>
    <h2>Ruby on Rails</h2>
    <p>Дано натуральное число n и целые числа a1 , a2 , . . . an . Написать программу, определяющую, есть ли среди заданной последовательности чисел отрезки (непрерывные подпоследовательности), состоящие из полных квадратов. Если есть, то подсчитать их количество и определить самый длинный из отрезков. Вывести на печать все отрезки, самый длинный из них и количество искомых отрезков. Если таких отрезков нет, то соответствующее сообщение. При составлении программы использовать функции.</p>

    <%= form_with url: calcs_url, method: :post, local: true, remote: false do |f| %>
      <table>
        <tr>
          <td><%= f.label :query_number, 'Введите количество элементов последовательности' %></td>
          <td><%= f.number_field :query_number, placeholder: "Количество элементов последовательности", value: "12" %></td>
        </tr>
        <tr>
          <td><%= f.label :query_sequence, 'Введите последовательность' %></td>
          <td><%= f.text_field :query_sequence, placeholder: "Последовательность", value: "1 4 25 64 43 16 59 10 12 13 81 121" %></td>
        </tr>
      </table>
      <br>
      <%= f.submit "Добавить запись:", id: 'calculate-btn' %>
    <% end %>
  </div>
</main>

app/views/calcs/_update_calc.html.erb
<main>
  <div>
  <p>
    <strong>id записи:</strong>
    <%= calc.id %>
  </p>
  <h3>Обновление этой записи calc (новые данные):</h3>
    <%= form_with url: "#{calcs_path}/#{calc.id}", method: :put do |f| %>
      <table>
        <tr>
          <td><%= f.label :query_number, 'Введите количество элементов последовательности' %></td>
          <td><%= f.number_field :query_number, placeholder: "Количество элементов последовательности", value: "#{calc.query_number}" %></td>
        </tr>
        <tr>
          <td><%= f.label :query_sequence, 'Введите последовательность' %></td>
          <td><%= f.text_field :query_sequence, placeholder: "Последовательность", value: "#{calc.query_sequence}" %></td>
        </tr>
      </table>
      <br>
      <%= f.submit "Обновить запись:", id: 'calculate-btn' %>
    <% end %>
  </div>
</main>

app/views/calcs/edit.html.erb
<h1>Editing calc</h1>

<%= render "update_calc", calc: @calc %>

<br>

<div>
  <%= link_to "Show this calc", @calc %> |
  <%= link_to "Back to calcs", calcs_path %>
</div>

<% flash.each do |type, msg| %>
  <% case type %>
  <% when "alert" then %>
    <% msg.each do |msg1| %>
      <% if msg1[0] %>
        <h3 style="color: red">Ошибка!</h3>
      <% end %>
      <% if msg1[1] %>
        <h3>Пояснение: <%= msg1[1] %></h3>
      <% end %>
      <% if msg1[2] %>
        <h3>Возможно этот символ вызвал ошибку: <%= msg1[2] %></h3>
      <% end %>
      <% if msg1[3] %>
        <h3>Входные данные, вызвавшие ошибку: <%= msg1[3] %></h3>
      <% end %>
    <% end %>
  <% else %>
    <h3><%= msg %></h3>
  <% end %>  
<% end %>

app/views/calcs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Calcs</h1>

<div id="calcs">
  <% @calcs.each do |calc| %>
    <div>
      <%= render calc %>
      <p>
        <%= link_to "Show this calc", calc %>
      </p>
      <p>
        Запись пользователя
        <%= link_to "#{User.find(calc.user_id).username}", User.find(calc.user_id) %>
      </p>
    </div>
  <% end %>
</div>

<p><%= link_to "New calc", new_calc_path %></p>
<p><%= link_to "Go to login page", root_path %></p>

app/views/calcs/new.html.erb
<h1>New calc</h1>

<%= render "form", calc: @calc %>

<br>

<div>
  <%= link_to "Back to calcs", calcs_path %>
</div>

<% flash.each do |type, msg| %>
  <% case type %>
  <% when "alert" then %>
    <% msg.each do |msg1| %>
      <% if msg1[0] %>
        <h3 style="color: red">Ошибка!</h3>
      <% end %>
      <% if msg1[1] %>
        <h3>Пояснение: <%= msg1[1] %></h3>
      <% end %>
      <% if msg1[2] %>
        <h3>Возможно этот символ вызвал ошибку: <%= msg1[2] %></h3>
      <% end %>
      <% if msg1[3] %>
        <h3>Входные данные, вызвавшие ошибку: <%= msg1[3] %></h3>
      <% end %>
    <% end %>
  <% else %>
    <h3><%= msg %></h3>
  <% end %>  
<% end %>

app/views/calcs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @calc %>

<div>
  <%= link_to "Edit this calc", edit_calc_path(@calc.id) %> |
  <%= link_to "Back to calcs", calcs_path %>

  <%= button_to "Destroy this calc", @calc, method: :delete %>
</div>