config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'session#login'
  resources :calcs
  post 'session/create'
  get 'session/logout'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab12Ipl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand navbar-light bg-light sticky-top">
      <div class="container-fluid">
        <div class="row w-100">
          <div class="col-9">
            Lab12Ipl
          </div>  
          <div class="col">
            <div class="container-fluid">
              <div class="row">
                <div class="col">
                  <% if signed_in? %>
                    <%= link_to "Выйти", session_logout_path %>
                  <% end %>
                </div>
                <div class="col">
                  <% if signed_in? %>
                    User: <strong><%= link_to "#{current_user.username}", current_user %></strong>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <div class="wrap">
      <%= yield %>
    </div>
  </body>
</html>